# Generated by Django 5.1.1 on 2024-09-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perpustakaan',
            name='penulis',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='perpustakaan',
            name='stok',
            field=models.IntegerField(default=1),
        ),
    ]
